# Generated by Django 3.1.2 on 2022-01-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtags', models.CharField(max_length=500)),
                ('namedE', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
